###
GET http://localhost:3000/cuentas

###

GET http://localhost:3000/cuentas/1

###

POST http://localhost:3000/cuentas
Content-Type: application/json

{
  "IdUsuario": 1,
  "IdTipoCuenta": 1,
  "IdSucursal": 1,
  "CBU": "0220053100012345678924",
  "Alias": "Davis.Fondo.Mansion",
  "Saldo": 40000,
  "Activa": true,
  "FechaApertura": "2025-10-29T14:30:00Z"
}

###
PUT  http://localhost:3000/cuentas/1
Content-Type: application/json

{
  "Alias": "Davis.Fondo.Mafia"
}

###Sucursales
GET http://localhost:3000/sucursales



###
GET http://localhost:3000/sucursales/4



###
PUT http://localhost:3000/sucursales/4
Content-Type: application/json

{
  "Estado": false 
}


###
POST http://localhost:3000/sucursales
Content-Type: application/json

{
    "Nombre": "hola",
    "Ciudad": "noway",
    "Direccion": "Av libre Impuestos 256",
    "Telefono": "12343542",
    "Email": "sucursal2@gmail.com",
    "Estado": true
}

###
DELETE http://localhost:3000/sucursales/3

###TipoCuentas

GET http://localhost:3000/tiposCuentas


###

GET http://localhost:3000/tiposCuentas/2

###
POST http://localhost:3000/tiposCuentas
Content-Type: application/json

{
  "Nombre": "Caja empresarial",
  "Descripcion": "No hay intereses",
  "PermiteCredito": true,
  "Moneda": "ARS",
  "TasaInteres": 0
}

###
PUT http://localhost:3000/tiposCuentas/3
Content-Type: application/json

{
  "Nombre": "Caja Sin interes"
}

###

DELETE http://localhost:3000/tiposCuentas/3


###Usuarios

GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/2

###
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
  "Nombre": "Calor"
}

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "Nombre": "Juan Gonzales",
  "DNI": "4012326",
  "Email": "juan.gonzales@gmail.com",
  "Telefono": "011-1234-5678",
  "Direccion": "Av. Siempre Viva 742",
  "Rol": "cliente",
  "FechaAlta": "2025-10-28T10:00:00.000Z",
  "Activo": true,
  "PasswordHash": "123",
  "IdSucursal": 4
}

###
DELETE http://localhost:3000/usuarios/3


