### Transacciones

GET http://localhost:3000/transacciones

###
GET http://localhost:3000/transacciones/1
###
POST http://localhost:3000/transacciones
Content-Type: application/json

{
  "idCuentaOrigen": 1,
  "idCuentaDestino": 2,
  "monto": 1500.50,
  "tipo": "transferencia",
  "descripcion": "Pago de servicios",
  "estado": "completado"
}

###
PUT http://localhost:3000/transacciones/1
Content-Type: application/json

{
  "descripcion": "Pago de servicios actualizado",
  "estado": "cancelado"
}

###
DELETE http://localhost:3000/transacciones/1