### Usuarios

GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/2

###
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
  "Nombre": "Calor"
}

###
POST http://localhost:3000/usuarios/register
Content-Type: application/json

{
  "Nombre": "Juan Gonzales",
  "DNI": "4012326",
  "Email": "juan.gonzales@gmail.com",
  "Telefono": "011-1234-5678",
  "Direccion": "Av. Siempre Viva 742",
  "Rol": "cliente",
  "FechaAlta": "2025-10-28T10:00:00.000Z",
  "Activo": true,
  "PasswordHash": "123",
  "IdSucursal": 1
}
###
DELETE http://localhost:3000/usuarios/7

###
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
  "Email": "juan.gonzales@gmail.com",
  "PasswordHash": "123"
}